name: Build Mesen

on: [push]

env:
  # I'm not a fan of the telemetry as-is, but this also suppresses some lines in the build log.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  # This removes even more spurious lines.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  macos:
    strategy:
      matrix:
        compiler: [clang]
        os: [macos-latest-xlarge]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: |
          brew install sdl2

      - name: Execute unit tests
        run: dotnet test --nologo

      # stderr is not detected as a TTY, so diagnostics are by default printed without colours;
      # forcing colours makes the log a little nicer to read.
      - name: Build Mesen
        run: |
          make -j$(nproc)
      
      - name: Zip Mesen.app
        run: |
          ditto -c -k --sequesterRsrc --keepParent bin/osx-x64/Release/osx-x64/publish/Mesen.app bin/osx-x64/Release/Mesen.app.zip

      - name: Upload Mesen
        uses: actions/upload-artifact@v3
        with:
          name: Mesen (macOS - ${{ matrix.os }})
          path: bin/osx-x64/Release/Mesen.app.zip
